### ISSUE TITLE
torch_sparse error

### ISSUE THREAD

**Issue by zemanet2020** [Anonnoname/G2GT_2#1]
I installed G2GT_2 as explained in README.
Installation proceeded without problems.
Then I change directory to src and commented the following line from train.sh:
#cd g2gt_github/src/

When I tried to execute train.sh, I got error messages.

`arg0: ./train.sh
exp_name: uspto
arch: --ffn_dim 1024 --hidden_dim 256 --dropout_rate 0.1 --intput_dropout_rate 0.05 --attention_dropout_rate 0.1 --n_layer 6 --peak_lr 2.5e-4 --end_lr 1e-6 --head_size 12 --weight_decay 0.00 --edge_type one_hop --warmup_updates 3000 --tot_updates 700000
seed: 0
batch_size: 5

Traceback (most recent call last):
  File "entry.py", line 5, in <module>
    from model import GraphFormer
  File "/opt/modeling/synthesis/G2GT_2/src/model.py", line 4, in <module>
    from data import get_dataset
  File "/opt/modeling/synthesis/G2GT_2/src/data.py", line 13, in <module>
    from custom_dataset import UsptoDataset
  File "/opt/modeling/synthesis/G2GT_2/src/custom_dataset.py", line 15, in <module>
    from torch_geometric.data import Dataset,InMemoryDataset
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch_geometric/utils/__init__.py", line 3, in <module>
    from .scatter import scatter
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 7, in <module>
    import torch_geometric.typing
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch_geometric/typing.py", line 37, in <module>
    import torch_sparse  # noqa
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch_sparse/__init__.py", line 40, in <module>
    from .tensor import SparseTensor  # noqa
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch/jit/_script.py", line 1128, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch/jit/_script.py", line 138, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
object has no attribute sparse_csc_tensor:
  File "/opt/anaconda310/envs/G2GT/lib/python3.7/site-packages/torch_sparse/tensor.py", line 520
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())

        return torch.sparse_csc_tensor(colptr, row, value, self.sizes())
               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

`

**Comment by magdidms** [comment]
how do you solve this problem?
please give an feedback if you got this
